#!/bin/sh

#apt-get install gvfs-bin

if [ ! -f "$1" ] ; then
	echo "$0 <file>"
	exit 1
fi

F=`basename "$1"`
D=`dirname "$1"`
N="${D}/_${F}"

echo "${F}" | egrep -q '^_'
if [ "$?" -eq "1" ]; then
	mv "$1" "${N}"
else
	N="$1"
fi

gvfs-set-attribute -t stringv "${N}" metadata::emblems generic

exec vlc --file-caching 4000 "${N}"

